//go:build !ignore_autogenerated

// Copyright 2026 Volker Theile
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskInfo) DeepCopyInto(out *DiskInfo) {
	*out = *in
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rotational != nil {
		in, out := &in.Rotational, &out.Rotational
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskInfo.
func (in *DiskInfo) DeepCopy() *DiskInfo {
	if in == nil {
		return nil
	}
	out := new(DiskInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskTelemetry) DeepCopyInto(out *DiskTelemetry) {
	*out = *in
	if in.TemperatureCelsius != nil {
		in, out := &in.TemperatureCelsius, &out.TemperatureCelsius
		*out = new(int)
		**out = **in
	}
	if in.PowerOnHours != nil {
		in, out := &in.PowerOnHours, &out.PowerOnHours
		*out = new(int64)
		**out = **in
	}
	if in.PowerCycleCount != nil {
		in, out := &in.PowerCycleCount, &out.PowerCycleCount
		*out = new(int64)
		**out = **in
	}
	if in.ReallocatedSectors != nil {
		in, out := &in.ReallocatedSectors, &out.ReallocatedSectors
		*out = new(int64)
		**out = **in
	}
	if in.PendingSectors != nil {
		in, out := &in.PendingSectors, &out.PendingSectors
		*out = new(int64)
		**out = **in
	}
	if in.PercentageUsed != nil {
		in, out := &in.PercentageUsed, &out.PercentageUsed
		*out = new(int)
		**out = **in
	}
	if in.AvailableSpare != nil {
		in, out := &in.AvailableSpare, &out.AvailableSpare
		*out = new(int)
		**out = **in
	}
	if in.CriticalWarning != nil {
		in, out := &in.CriticalWarning, &out.CriticalWarning
		*out = new(int)
		**out = **in
	}
	if in.MediaErrors != nil {
		in, out := &in.MediaErrors, &out.MediaErrors
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskTelemetry.
func (in *DiskTelemetry) DeepCopy() *DiskTelemetry {
	if in == nil {
		return nil
	}
	out := new(DiskTelemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
	if in.AttributeID != nil {
		in, out := &in.AttributeID, &out.AttributeID
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalDisk) DeepCopyInto(out *PhysicalDisk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalDisk.
func (in *PhysicalDisk) DeepCopy() *PhysicalDisk {
	if in == nil {
		return nil
	}
	out := new(PhysicalDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PhysicalDisk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalDiskList) DeepCopyInto(out *PhysicalDiskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PhysicalDisk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalDiskList.
func (in *PhysicalDiskList) DeepCopy() *PhysicalDiskList {
	if in == nil {
		return nil
	}
	out := new(PhysicalDiskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PhysicalDiskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalDiskSpec) DeepCopyInto(out *PhysicalDiskSpec) {
	*out = *in
	if in.Smartmontools != nil {
		in, out := &in.Smartmontools, &out.Smartmontools
		*out = new(SmartmontoolsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalDiskSpec.
func (in *PhysicalDiskSpec) DeepCopy() *PhysicalDiskSpec {
	if in == nil {
		return nil
	}
	out := new(PhysicalDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalDiskStatus) DeepCopyInto(out *PhysicalDiskStatus) {
	*out = *in
	if in.LastDataCollectedTime != nil {
		in, out := &in.LastDataCollectedTime, &out.LastDataCollectedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Info.DeepCopyInto(&out.Info)
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(DiskTelemetry)
		(*in).DeepCopyInto(*out)
	}
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]Finding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalDiskStatus.
func (in *PhysicalDiskStatus) DeepCopy() *PhysicalDiskStatus {
	if in == nil {
		return nil
	}
	out := new(PhysicalDiskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmartctlSpec) DeepCopyInto(out *SmartctlSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmartctlSpec.
func (in *SmartctlSpec) DeepCopy() *SmartctlSpec {
	if in == nil {
		return nil
	}
	out := new(SmartctlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmartmontoolsSpec) DeepCopyInto(out *SmartmontoolsSpec) {
	*out = *in
	if in.Smartctl != nil {
		in, out := &in.Smartctl, &out.Smartctl
		*out = new(SmartctlSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmartmontoolsSpec.
func (in *SmartmontoolsSpec) DeepCopy() *SmartmontoolsSpec {
	if in == nil {
		return nil
	}
	out := new(SmartmontoolsSpec)
	in.DeepCopyInto(out)
	return out
}
